// Source: "QA checklist and test results PN V2 19_09_26.docx" — only FAIL / PARTIAL /
// BLOCKED / NOT TESTED items (passing checks are omitted). Keep in sync with
// docs/V2_QA_CHECKLIST.md in the project root. Update `status` as fixes land.

export type QaStatus = "todo" | "in_progress" | "done";
export type QaPriority = "CRIT" | "HIGH" | "STD";
export type QaResult = "FAIL" | "PARTIAL" | "BLOCKED" | "NOT TESTED";

export type QaItem = {
  id: string;
  pri: QaPriority;
  qa: QaResult;
  title: string;
  issue: string;
  fix: string;
  status: QaStatus;
  /** Same underlying defect as another item — resolves with it. */
  dupOf?: string;
  note?: string;
};

export type QaSection = { id: string; title: string; items: QaItem[] };

export const qaChecklistMeta = {
  title: "V2 QA Checklist — 19 Sep 2026",
  source: "QA checklist and test results PN V2 19_09_26.docx",
  lastUpdated: "2026-09-28",
};

export const qaSections: QaSection[] = [
  {
    id: "key",
    title: "0. Key regression checks",
    items: [
      {
        id: "K02",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "First request says 'Request Rematch'",
        issue: "First-ever request button reads 'Request Rematch'.",
        fix: "Button = 'Request Match' for first request; 'Request Rematch' only after a previous match ended; 'Open Chat' while matched.",
        note: "Modal/button now 'Request Match' for first request, 'Request Rematch' only after an ended match, 'Open Chat' while matched.",
      },
      {
        id: "K03",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Intro message 30-char limit",
        issue: "Allows 31+ chars; counter shows 0/250.",
        fix: "Enforce 30-char limit client + server; counter 0/30; recipient can read it.",
        note: "30-char limit enforced client (0/30 counter) + server (400 on 31+). Verified via API.",
      },
      {
        id: "K05",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Stale request action accepted",
        issue: "Tab A accepted; stale Tab B could still decline → match destroyed, 'Conversation no longer found'.",
        fix: "Server must only transition from 'pending' (conditional update); reject stale accept/decline/withdraw with a clear message.",
        note: "Accept/decline/withdraw are atomic pending-only transitions; stale tab gets 409 + refresh. Verified via API on match #193.",
      },
      {
        id: "K06",
        pri: "CRIT",
        qa: "PARTIAL",
        status: "done",
        title: "Blocked old chat shows message as sent",
        issue: "Stale chat briefly shows the sent message, then 'Chat not found'.",
        fix: "Disable composer immediately on block (realtime) and never optimistic-render a message the server rejected.",
        note: "Block broadcasts match:closed → composer locks instantly with 'This match has ended'; a rejected send is removed and locks the chat instead of flashing 'Chat not found'.",
      },
      {
        id: "K08",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Chat draft + 'Draft:' preview",
        issue: "No draft feature.",
        fix: "Persist unsent text per chat; Chats list shows 'Draft: <preview>'.",
        note: "Unsent text is saved per conversation on the device, restored when the chat reopens, and the Chats list shows 'Draft: <preview>'. Cleared on send. Verified locally.",
      },
      {
        id: "K09",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Keyboard hides chat header",
        issue: "Opening keyboard (portrait + landscape) pushes header off-screen.",
        fix: "Chat layout sized to visual viewport; header + composer stay visible. (Also M02, M03, F07)",
        note: "Mobile thread is pinned to the visual viewport (visualViewport height/offset) + interactive-widget=resizes-content, so header + composer stay visible with the keyboard open in portrait and landscape. Verified with a shrunk viewport; needs real iOS/Android retest.",
      },
      {
        id: "K10",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Owner can't see own photo",
        issue: "Owner can't view own photo in Edit/Preview; mobile loading inconsistent.",
        fix: "Owner always gets signed unblurred URLs for own photos (main + 2 optional). (Also P01, PH02)",
        note: "Root cause: owner pages rendered the old PUBLIC storage URL but the bucket is private → every owner photo failed. Owner views + gallery now use signed URLs and are never blurred to the owner. Verified live on My Profile + Edit.",
      },
      {
        id: "K11",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Push notification icon inconsistent",
        issue: "Bell / stacked-square / solid square icons depending on type.",
        fix: "Use PN monochrome badge icon + PN logo icon for every push type incl. grouped.",
        note: "Pushes are now data-only, so the PN service worker draws every one (message, request, photo, grouped) the same way: PN logo / sender's blurred photo as the icon and a new monochrome PN heart badge (pn-badge-96.png) for the Android status bar — the old full-colour badge was the 'solid square'. Needs an Android device check.",
      },
      {
        id: "K13",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Activity wording + Just Joined",
        issue: "Status matches but shows precise minutes/hours.",
        fix: "See B13 / B14.",
        dupOf: "B13",
        note: "Resolved with B13 + B14.",
      },
    ],
  },
  {
    id: "reg",
    title: "1. Registration & onboarding",
    items: [
      {
        id: "R04",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "City must be a real selectable place",
        issue: "Can type a fake city; no dropdown.",
        fix: "Searchable city/area dropdown; free text not accepted.",
        note: "City is a searchable dropdown of real towns/cities (Google Places), narrowed to the chosen country, in signup and Edit Profile. Continue/Save stay blocked until a city is picked from the list; the server also rejects invented cities. Verified: 'Fakeville Zzz' rejected (UI + both APIs), 'Lond' → London selectable.",
      },
    ],
  },
  {
    id: "profile",
    title: "2. My Profile / Edit Profile",
    items: [
      {
        id: "P01",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Uploaded photo not shown to owner",
        issue: "Upload works but owner can't see it.",
        fix: "See K10.",
        dupOf: "K10",
        note: "Resolved with K10.",
      },
      {
        id: "P03",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Whitespace-only Profession / About Me",
        issue: "Whitespace saves as content.",
        fix: "Trim + reject whitespace-only (client + server).",
        note: "All profile text fields are trimmed server-side; whitespace-only is saved as empty.",
      },
      {
        id: "P05",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Long profession validation message",
        issue: "Over-long blocked silently.",
        fix: "Show a field-specific validation message.",
        note: "Field-specific limits with clear messages, e.g. 'Profession is too long — please keep it under 100 characters.'",
      },
      {
        id: "P10",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Unsaved-changes leave warning",
        issue: "No warning when leaving My Profile with unsaved edits.",
        fix: "Confirm dialog on in-app navigation + beforeunload.",
        note: "Leaving My Profile with unsaved edits (in-app link, browser Back, closing/reloading the tab) shows 'Discard unsaved changes?' — Keep editing / Leave without saving. Pause saves instantly so never counts. Verified locally.",
      },
    ],
  },
  {
    id: "browse",
    title: "3. Browse, activity & filters",
    items: [
      {
        id: "B02",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Restore Browse scroll on close",
        issue: "'X' on full profile returns to top of Browse.",
        fix: "Restore previous scroll position; change 'X' to '←' button.",
        note: "Scroll position restored on return (incl. page 1, saved while scrolling); full-profile 'X' replaced with a '←' back button.",
      },
      {
        id: "B04",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Online state never expires",
        issue: "Inactive 5+ min still 'Online' and ranked top.",
        fix: "Expire live state after ~3–5 min of no meaningful activity; no 'Online' label (show 'Active today'); no exact last-seen.",
        note: "Heartbeat now needs real interaction (tap/key/scroll/foreground) in the last 3 min, so an idle open app stops being 'active' after ~3–5 min; 'Online' label removed.",
      },
      {
        id: "B07",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Distance filter not applied",
        issue: "Profiles outside radius (Birmingham) still shown.",
        fix: "Filter by real distance from saved/selected coords before ranking.",
        note: "Root cause: the Browse search centre overwrote the same columns other members' distance searches used as that person's home, and 97% of members had no coordinates. Added separate home_lat/home_lng (set at signup, updated on city change, backfilled for 368 profiles from their city). Verified: Birmingham 10mi → 16 profiles, all Birmingham/West Midlands.",
      },
      {
        id: "B08",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Salah not on profile; remove Appearance filter",
        issue: "Salah filter exists but Salah pattern not shown on full profile.",
        fix: "Show Salah pattern on full profile; remove Appearance advanced filter.",
        note: "Salah pattern now shows in the Faith section of the full profile (e.g. PNF318: 'Almost always – …'). Note: 241/567 profiles have a Salah answer (V1 data) — signup/Edit Profile don't ask for it yet.",
      },
      {
        id: "B09",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Basic sees Gold-only filters",
        issue: "Basic can use Religious Practice + Open to Relocation.",
        fix: "Gate those (and audit all Gold filters) for Basic, client + server. (Also F04)",
        note: "Religious Practice + Open to Relocation are now Gold-only: locked in the UI, stripped for Basic, and ignored server-side for Basic.",
      },
      {
        id: "B10",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Gold AI Compatibility before request",
        issue: "Gold sees analysis only after sending a request.",
        fix: "Show compatibility on eligible profile open, before request.",
        note: "Gold members see AI Compatibility the moment they open an eligible profile — before any Match Request. The breakdown is computed instantly (no waiting on AI). Verified: PNM574 (Gold) opening PNF318.",
      },
      {
        id: "B12",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Filter exhaustion message",
        issue: "Not implemented.",
        fix: "Show \"You've seen everyone matching your preferences\" then expanded results.",
        note: "'You've seen everyone matching your preferences' divider, then Browse continues with expanded results instead of ending. Verified via API: strict 15 → +58 → +4, zero overlap.",
      },
      {
        id: "B13",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Simplified activity wording",
        issue: "'Active 50 min ago', '7 hrs ago' etc.",
        fix: "Only: Active today / Active yesterday / Active this week / Active recently. Exact timestamps used for ranking only.",
        note: "Only 'Active today / Active yesterday / Active this week / Active recently / Not recently active' (Europe/London days) on cards + full profile; no minutes/hours or 'Online'. Exact timestamp still used for ranking. Verified via Browse API.",
      },
      {
        id: "B14",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Just Joined as separate badge",
        issue: "No Just Joined badge.",
        fix: "Show '✨ Just Joined' alongside (not instead of) activity on card + full profile.",
        note: "'✨ Just Joined' is a separate badge next to the activity status on the card and full profile.",
      },
      {
        id: "B15",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Just Joined boost too strong",
        issue: "New inactive profiles outrank active established ones.",
        fix: "Reduce Just Joined weight to a small tie-breaker.",
        note: "Just Joined boost stays a small tie-breaker inside the same activity bucket; the reported jump came from idle tabs counting as activity (fixed in B04). Verified order: activity first, JJ never above more-active members.",
      },
      {
        id: "B16",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Browse memory",
        issue: "Same top profiles every visit.",
        fix: "Down-rank recently viewed/opened/skipped within similar-activity bands.",
        note: "Browse Memory: inside the same activity bucket, members already shown (+ more if opened) sink below unseen similarly-active members. Never crosses activity buckets.",
      },
      {
        id: "B17",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Limited rotation",
        issue: "Similar-activity profiles never rotate.",
        fix: "Seeded rotation within activity bands; never lifts clearly less active above more active.",
        note: "Controlled rotation among similarly active members, re-seeded every 4-hour session window; stable within a session (verified identical order on reload).",
      },
      {
        id: "B20",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "'New activity available' prompt",
        issue: "No prompt; list unaware of fresher results.",
        fix: "Keep list stable; show 'New activity available — Refresh' pill.",
        note: "List stays stable; every 60s (tab visible) Browse checks who became active since load and shows 'New activity available — Refresh' if it's someone not already near the top.",
      },
      {
        id: "B21",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Controlled preference expansion",
        issue: "Not implemented.",
        fix: "After exhaustion relax distance → small age widen → other soft prefs.",
        note: "Gradual, cumulative relaxation: distance first → age ±3 → other soft preferences. Each stage excludes what earlier stages matched.",
      },
      {
        id: "B22",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Expanded results transparency + hard filters",
        issue: "Not implemented.",
        fix: "Label expanded results; never relax hard rules (blocked, suspended, hidden, ineligible, gender).",
        note: "Expanded results are labelled per card ('Outside your distance' / 'Just outside your age range' / 'Outside some of your preferences') and every stage still goes through the hard-eligibility base filter (approved, not hidden/paused, not suspended — newly enforced — opposite gender, not blocked, not self).",
      },
      {
        id: "B23",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Sort options",
        issue: "Quick sorts wrong.",
        fix: "Rename 'Best Match' → 'Compatibility'; remove 'Most Active'; keep 'Recently Active'.",
        note: "Sort menu: Recently active (default activity ranking), Compatibility (Gold; renamed from Best Match), Age ↑/↓. \"Most active\" removed. Compatibility sort now weighs activity so long-inactive members can't dominate.",
      },
      {
        id: "B26",
        pri: "HIGH",
        qa: "NOT TESTED",
        status: "done",
        title: "Two-way compatibility",
        issue: "Not tested by QA.",
        fix: "Verify compatibility checks preferences in both directions.",
        note: "Checked both directions: each member's age against the other's age range, openness to the other's marital history, and education vs the other's education preference. A one-sided fit is never shown as aligned. Verified with A-fits-B / B-doesn't-fit-A cases from both viewpoints.",
      },
      {
        id: "B27",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Compatibility sections, remove %",
        issue: "Shows '80% compatible' bar; explanation is a placeholder.",
        fix: "Remove % and bar; written breakdown: Aligned / Worth Discussing / Not Enough Information from real data only.",
        note: "Percentage score and bar removed everywhere (profile, Browse cards, Requests). AI Compatibility is now a written breakdown: Aligned / Worth discussing / Not enough information, built only from real profile + preference data — missing data goes to Not enough information, never counted as alignment. Plus a short AI summary written only from those findings.",
      },
      {
        id: "B28",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Compatibility consistency",
        issue: "Does not function.",
        fix: "Cache result per pair; only regenerate when either profile changes.",
        note: "Breakdown is rule-based and deterministic, so the same pair always shows the same result; the AI summary is cached per pair and only regenerated when either profile's relevant data (or the rules) change. Verified: repeated opens identical.",
      },
      {
        id: "B29",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "AI explanation reliability",
        issue: "Some stuck on 'AI explanation will appear after the first compatibility analysis'.",
        fix: "Generate reliably on open; keep safe wording.",
        note: "Safe wording kept (prompt forbids character/suitability/marriage-success claims; unsafe words and % are filtered out). The breakdown no longer depends on AI, so nothing is ever stuck on a placeholder; a failed AI summary is retried on the next open instead of being locked in. Verified: summary generated and cached.",
      },
      {
        id: "B30",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "AI explanation reliability (Free gating OK)",
        issue: "Free gating passes; generation unreliable.",
        fix: "See B29.",
        dupOf: "B29",
        note: "Resolved with B29. Free/Basic members still see no AI Compatibility (verified: Basic account opening a profile gets no analysis).",
      },
    ],
  },
  {
    id: "location",
    title: "4. Location & distance",
    items: [
      {
        id: "L02",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "'Search this area' not applied",
        issue: "Map/pin fine; Browse still shows whole UK.",
        fix: "Selected coords saved and used as distance-filter centre.",
        note: "Resolved with B07 — the confirmed map area is the search centre; results use members' real home coordinates.",
      },
      {
        id: "L03",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Location search doesn't move map",
        issue: "Selected Birmingham; map stayed on London.",
        fix: "Selecting a search result re-centres map + pin and updates label.",
        note: "Picking a search result moves map + pin in one camera move (panTo followed by setZoom cancelled the pan).",
      },
    ],
  },
  {
    id: "requests",
    title: "5. Requests, matching & tokens",
    items: [
      {
        id: "Q02",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Request badges realtime + consistent",
        issue: "Badge issues across bottom nav and ☰ menu.",
        fix: "Live unread count shared by bottom nav + ☰ menu (red dot on closed icon); persists until viewed.",
        note: "App-wide LiveUpdates layer refreshes the shared badge counts instantly on request/message events; ☰ red dot now uses live counts too.",
      },
      {
        id: "Q03",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Sender not updated on accept",
        issue: "Male (sender) had to refresh to see match.",
        fix: "Realtime update of Sent/Matches + badges when request accepted.",
        note: "Accept broadcasts request:update to both users → sender's Sent/Matches + badges refresh live; also shows 'Match accepted' banner.",
      },
      {
        id: "Q05",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Withdrawn request stays in Incoming",
        issue: "Badge clears but card stays until refresh.",
        fix: "Realtime removal from recipient Incoming.",
        note: "Withdraw broadcasts request:update → recipient's Incoming refreshes live.",
      },
      {
        id: "Q06",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Sent states show dates, not last-seen",
        issue: "Cards show '31m ago' (last activity).",
        fix: "Show 'Requested/Matched/Declined/Withdrawn on <date, time>'; keep declined/withdrawn in history.",
        note: "Request and match cards show 'Requested / Matched / Declined / Withdrawn / Ended on 22 Sep, 14:30' in the member's local time — no more '31m ago'. New accepted_at column (set on accept, backfilled for 71 existing matches). Declined/withdrawn stay in history. Verified.",
      },
      {
        id: "Q08",
        pri: "CRIT",
        qa: "PARTIAL",
        status: "done",
        title: "End Match realtime",
        issue: "Other side's chat stays open; send → 'Chat not found'.",
        fix: "Realtime: disable composer + 'This match has ended.'",
        note: "End Match broadcasts match:closed to the thread + both users → other side's composer disables immediately with 'This match has ended'. Needs QA retest (not run live to protect the QA match).",
      },
      {
        id: "Q09",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Rematch rules",
        issue: "30-day block; wrong wording.",
        fix: "Remove 30-day cooldown; one Match Token per request/rematch; rematch = new pending request; no auto-reopen of old chat.",
        note: "Rematch = new pending request costing 1 normal Match Token; no rematch-token balance; no 30-day cooldown after an ended match.",
      },
      {
        id: "Q12",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Block clears requests realtime",
        issue: "Old request stays visible; Accept → 'Request not available'.",
        fix: "On block remove/disable related requests on both sides in realtime.",
        note: "Block cancels pending requests and broadcasts request:update → open Requests pages refresh live.",
      },
    ],
  },
  {
    id: "chat",
    title: "6. Chat & messaging",
    items: [
      {
        id: "C02",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Tick states inside bubble",
        issue: "No single sent tick; ticks outside bubble; read receipt 1–2s.",
        fix: "Sent ✓ / delivered ✓✓ / read (blue) ✓✓; time + ticks bottom-right inside bubble; faster receipts.",
        note: "Clock while sending → ✓ once the server confirms → grey ✓✓ when the recipient's app receives it → crimson ✓✓ when read. Time + ticks sit bottom-right inside the bubble. Delivered state needs a two-device QA retest.",
      },
      {
        id: "C03",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Typing indicator",
        issue: "Delay; shows at top; uses names.",
        fix: "Bottom above composer; profile IDs not names (header, bubble, list); prompt clear.",
        note: "Typing indicator sits at the bottom just above the composer, uses the profile ID (header, bubble, list), and clears ~1s after typing stops.",
      },
      {
        id: "C04",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Drag-to-reply + desktop menu clipping",
        issue: "No finger-tracking swipe reply; desktop menu cropped by header.",
        fix: "WhatsApp-style drag-right reply with haptic at threshold; fix menu clipping.",
        note: "WhatsApp-style drag-right-to-reply follows the finger with a haptic tick at the threshold; the message menu opens below the bubble when there's no room above, so it's no longer clipped by the header. Verified locally.",
      },
      {
        id: "C05",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Reaction placement + speed",
        issue: "1–2s delay; placement gap.",
        fix: "Outgoing: bottom-right under ticks; incoming: bottom-left overlapping bubble; faster sync.",
        note: "Reactions tuck under the bubble edge — outgoing bottom-right under the time/ticks, incoming bottom-left overlapping the bubble.",
      },
      {
        id: "C07",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Message timestamps + date separators",
        issue: "No per-message time.",
        fix: "Time inside bubble; Today / Yesterday / date separators; local time.",
        note: "Local HH:MM inside every bubble; Today / Yesterday / 'Wed 9 Sept' separators grouped by the member's local day.",
      },
      {
        id: "C08",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Unread badges + divider",
        issue: "Left nav badge doesn't clear; no divider.",
        fix: "Clear everywhere on read in realtime; 'N unread messages' divider.",
        note: "Badge sync done earlier; now an 'N unread messages' divider marks where unread starts when a chat opens.",
      },
      {
        id: "C11",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Chat ↔ Profile finger-tracking swipe",
        issue: "Generic swipe, no drag tracking.",
        fix: "Continuous finger-tracking pane drag with threshold + snap-back. (Also M04, M05)",
        note: "Chat and Profile sit on one track that follows the finger; releasing past a third (or a quick flick) switches, otherwise it springs back. Vertical scrolling locks out the pane swipe. Verified locally with touch drags.",
      },
      {
        id: "C12",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Scroll + draft preserved on swipe",
        issue: "Returns jump to latest message.",
        fix: "Keep chat mounted; restore scroll; keep draft.",
        note: "Both panes stay mounted, so switching Chat ↔ Profile keeps the scroll position and the draft. Verified locally.",
      },
      {
        id: "C14",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Offline send shows false delivery",
        issue: "Offline messages showed ✓✓ then vanished.",
        fix: "Never show ticks without server ack; local queue + retry; idempotent client ids.",
        note: "Every send goes through a device outbox with a client id: offline messages show a clock (never ticks), survive closing the app, auto-send on reconnect, and the server dedupes retries. Failed sends show 'Not sent — tap to retry'. Verified locally (offline → reconnect → exactly one copy).",
      },
    ],
  },
  {
    id: "wali",
    title: "7. Wali oversight & family involvement",
    items: [
      {
        id: "W03",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Wali view sender identification",
        issue: "Can't tell who sent which message.",
        fix: "Header 'PNFxxx's chat with PNMxxx'; distinct bubble sides/colours with IDs.",
        note: "Wali view header reads 'PNF563's chat with PNM574'; the member you oversee is always on the right in crimson, the match on the left in grey, each run labelled with the sender's profile ID; quoted replies show who they quote. Verified locally.",
      },
      {
        id: "W05",
        pri: "HIGH",
        qa: "FAIL",
        status: "todo",
        title: "Three wali modes",
        issue: "'Oversight + Notifications' missing.",
        fix: "Modes: Oversight Only / Oversight + Notifications / Join Conversation; choose at invite; editable later.",
      },
      {
        id: "W06",
        pri: "HIGH",
        qa: "FAIL",
        status: "todo",
        title: "Join Conversation",
        issue: "Needs refresh; wali can't send; quoted replies broken.",
        fix: "Realtime join; oversight pill; wali can send in Join mode; show quoted replies.",
      },
      {
        id: "W07",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Revoking wali not enforced live",
        issue: "Revoked wali kept scrolling + received a new message.",
        fix: "Realtime revoke → unsubscribe + 'Access revoked' screen; server rejects revoked sessions/links.",
        note: "Wali now gets live messages on its own per-link topic; server only publishes to non-revoked links. Revoke pushes 'Access revoked' instantly + 20s/focus session re-check. Verified live: page wiped, post-revoke message never arrived.",
      },
      {
        id: "W09",
        pri: "STD",
        qa: "FAIL",
        status: "todo",
        title: "Wali activity log",
        issue: "No log.",
        fix: "Activity log in Wali Settings: invites, accepts, views, permission changes, revokes.",
      },
      {
        id: "W10",
        pri: "HIGH",
        qa: "FAIL",
        status: "todo",
        title: "Ready to Involve Family",
        issue: "Feature missing.",
        fix: "Yes / Not Yet / End; mutual readiness; only female shares wali contact after mutual Yes; stage indicators.",
      },
    ],
  },
  {
    id: "photos",
    title: "8. Photo privacy & timed reveal",
    items: [
      {
        id: "PH01",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Photos not loading on Browse / profile",
        issue: "Photos don't display, blur can't be verified.",
        fix: "Fix photo loading; confirm blur holds on card, full profile and enlarge.",
        note: "Unmatched full profile now shows the signed server-blurred derivative (was hidden entirely + broken public URL). Original never reaches the browser. Verified live.",
      },
      {
        id: "PH02",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Owner sees own photos",
        issue: "See K10.",
        fix: "See K10.",
        dupOf: "K10",
        note: "Resolved with K10.",
      },
      {
        id: "PH03",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Reveal confirmation",
        issue: "No confirm step.",
        fix: "Confirm popup explaining 60s one-time view; cancel doesn't start timer.",
        note: "Confirm step ('Start Viewing' / 'Not Now', explains 1-minute session) now reachable from Chat AND the matched member's full profile; Not Now doesn't start the timer.",
      },
      {
        id: "PH04",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Smooth countdown",
        issue: "Stutters / pauses.",
        fix: "Derive remaining time from fixed expiry timestamp; rAF/interval render only.",
        note: "Countdown derived from a fixed expiry timestamp (250ms render tick, re-sync on tab focus); no more restart on every 4s poll. Trigger label also ticks locally.",
      },
      {
        id: "PH05",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Black screen + timer pauses on close",
        issue: "Viewer sometimes black; closing pauses timer.",
        fix: "Fix image load (error state); timer keeps running while closed; server-enforced expiry.",
        note: "Black screen: image route cut from ~8 serial DB trips to 1 + parallel (warm 2–3.7s → ~1.1s), Start returns the viewer payload, viewer shows loading/error states. Viewer portals to <body> (no clipping). Timer is server-authoritative and keeps running while closed.",
      },
      {
        id: "PH06",
        pri: "CRIT",
        qa: "BLOCKED",
        status: "done",
        title: "Expiry re-blurs (chat + profile share session)",
        issue: "Black screen; profile entry has no reveal access.",
        fix: "One shared 60s session for Chat + Profile; both re-blur at expiry.",
        note: "Same share/session is exposed on Chat and the matched member's full profile (one server clock); both blur at expiry.",
      },
      {
        id: "PH07",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Multi-photo counter + navigation",
        issue: "No 1/3 counter.",
        fix: "Counter, swipe (mobile) / arrows (desktop), shared timer.",
        note: "Counter 1/N, swipe on mobile, arrows + keyboard on desktop, shared timer.",
      },
      {
        id: "PH09",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Foreground reveal banner",
        issue: "Push OK, no in-app banner.",
        fix: "In-app banner (shared system with N01/N02).",
        dupOf: "N01",
        note: "When a match shares private photos, the recipient gets a WhatsApp-style in-app banner anywhere in PN ('PNF563 shared private photos — Tap to view'); tapping opens that chat and the Start Viewing confirm. While PN is open and banners are on, the foreground OS push is skipped (no duplicate); background push unchanged. Verified locally.",
      },
      {
        id: "PH10",
        pri: "HIGH",
        qa: "FAIL",
        status: "in_progress",
        title: "Wali photo reveal access",
        issue: "Wali can't view permitted reveal.",
        fix: "Wali viewer bound to same session/expiry; realtime grant/revoke.",
        note: "Wali uses the same fixed viewer (black screen/timer fixes apply). Still todo: realtime grant/revoke update in wali portal; needs retest.",
      },
    ],
  },
  {
    id: "notif",
    title: "9. Notifications, FCM & PWA",
    items: [
      {
        id: "N01",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "In-app message banner",
        issue: "Not implemented.",
        fix: "WhatsApp-style top banner: sender ID + preview, tap → chat; suppressed when in that chat.",
        note: "WhatsApp-style in-app banner (sender ID + preview, tap → chat, suppressed inside that chat). Verified live on Browse.",
      },
      {
        id: "N02",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "In-app request banner",
        issue: "Not implemented.",
        fix: "'PNM582 sent you a Match Request' banner, tap → Incoming; same system as N01.",
        note: "Same banner system: 'PNMxxx sent you a Match Request' → Incoming; plus 'accepted your request' → chat.",
      },
      {
        id: "N03",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Push branding",
        issue: "Old V1 icon, shows vercel domain.",
        fix: "New PN logo, 'Pashtun Nikah' title, blurred sender photo (Android), keep ID + preview.",
        note: "PN logo + monochrome PN badge on every push; the sender's server-blurred photo is the large icon where Android supports it; profile ID + privacy-safe preview kept. The small 'vercel.app' origin line is drawn by Chrome itself — it only becomes 'Pashtun Nikah' when PN is installed as an app (PWA) or moves to its own domain.",
      },
      {
        id: "N07",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Badge update speed",
        issue: "~20s delay (polling).",
        fix: "Drive badges from realtime events, not polling.",
        note: "Badges refresh on realtime events (message, read, request) instead of waiting for the 45s poll.",
      },
      {
        id: "N08",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Approval notification",
        issue: "None sent on admin approval.",
        fix: "Push + bell + banner on approval; deep link to Overview; live status update.",
        note: "Admin approval → push + bell ('Your profile is approved', opens Overview) + in-app banner, and the member's open tabs refresh their status live (no re-login). Admin calls a signed web endpoint — needs INTERNAL_API_SECRET set to the same value on BOTH Vercel projects. Verified locally.",
      },
      {
        id: "N09",
        pri: "STD",
        qa: "FAIL",
        status: "todo",
        title: "Wali notifications",
        issue: "Wali gets none.",
        fix: "Per-mode wali notifications; stop on revoke.",
      },
      {
        id: "N10",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "In-app banner toggle",
        issue: "Not added.",
        fix: "Settings → Notifications toggle, persisted.",
        note: "Settings → Notifications → 'In-app notification banners' toggle, stored server-side (notification_preferences.in_app_banners).",
      },
    ],
  },
  {
    id: "settings",
    title: "10. Settings & account safety",
    items: [
      {
        id: "S01",
        pri: "STD",
        qa: "PARTIAL",
        status: "todo",
        title: "Settings structure",
        issue: "Needs regrouping.",
        fix: "Remove View Profile / Profile Status; Account & Membership; Notifications; Privacy & Safety (Blocked shortcut); Visibility+Pause combined; Delete Account last.",
      },
      {
        id: "S03",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Pause reflects in Browse live",
        issue: "Others must refresh.",
        fix: "Realtime remove paused profile from others' Browse.",
        note: "Pausing (or admin hide/suspend) removes the member's card from every open Browse instantly via a shared live channel. Verified locally: card disappeared without refresh.",
      },
      {
        id: "S04",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Reactivate reflects in Browse live",
        issue: "Others must refresh.",
        fix: "See S03.",
        dupOf: "S03",
        note: "Resuming re-checks the member against each viewer's own filters and slots the card back in at the top, live. Verified locally. (Also fixed a URL bug that broke expanded results and 'New activity' checks with default filters.)",
      },
      {
        id: "S06",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Unblocked member missing from Browse",
        issue: "After unblock, profile still hidden.",
        fix: "Fully clear block both ways; restore discovery (no match restore).",
        note: "Block→unblock→Browse verified with the QA pair. QA data shows PNF568 still blocking PNM581 (19 Sep) — only the member who blocked can unblock, from their own Settings → Privacy.",
      },
      {
        id: "S10",
        pri: "CRIT",
        qa: "PARTIAL",
        status: "done",
        title: "Multi-tab account switch",
        issue: "Other tabs keep old account data.",
        fix: "Broadcast auth change across tabs; clear caches and reload.",
        note: "Tabs announce their signed-in account over BroadcastChannel + re-check on focus; a tab showing a different/old account reloads immediately. Verified live with two tabs switching female→male.",
      },
    ],
  },
  {
    id: "mobile",
    title: "11. Mobile navigation & swipe",
    items: [
      {
        id: "M02",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Portrait chat keyboard",
        issue: "Header disappears.",
        fix: "See K09.",
        dupOf: "K09",
        note: "Resolved with K09.",
      },
      {
        id: "M03",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Landscape chat keyboard",
        issue: "Header pushed away.",
        fix: "See K09.",
        dupOf: "K09",
        note: "Resolved with K09.",
      },
      {
        id: "M04",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Vertical scroll triggers swipe",
        issue: "Slight sideways movement switches page.",
        fix: "Direction lock — vertical wins; see C11.",
        dupOf: "C11",
        note: "Resolved with C11.",
      },
      {
        id: "M05",
        pri: "STD",
        qa: "FAIL",
        status: "done",
        title: "Incomplete swipe snap-back",
        issue: "Short swipe still navigates.",
        fix: "See C11.",
        dupOf: "C11",
        note: "Resolved with C11.",
      },
      {
        id: "M06",
        pri: "STD",
        qa: "PARTIAL",
        status: "done",
        title: "Photo carousel black + clipped",
        issue: "Black screen, cropped by header.",
        fix: "See PH05 / PH07.",
        dupOf: "PH05",
        note: "Resolved with PH05 (portal overlay + load states).",
      },
    ],
  },
  {
    id: "admin",
    title: "12. Admin & chat moderation",
    items: [
      {
        id: "A02",
        pri: "HIGH",
        qa: "PARTIAL",
        status: "done",
        title: "Report reason popup",
        issue: "Report submits instantly with no reason.",
        fix: "Popup: reason dropdown + required details; admin sees IDs + context.",
        note: "Report (member or message) opens a popup: reason dropdown + required details (min 10 chars); server rejects reports without them. Stores category, details, conversation and reported message; admin Reports shows profile IDs, reason, details, the message and a link to the conversation. Verified locally (admin page type-checked; not viewed — admin login needed).",
      },
      {
        id: "A03",
        pri: "HIGH",
        qa: "FAIL",
        status: "todo",
        title: "Moderation actions",
        issue: "Warn does nothing; Resolve = Dismiss.",
        fix: "Warn → member sees warning + history; Resolve vs Dismiss distinct; log admin/action/reason/time.",
      },
    ],
  },
  {
    id: "final",
    title: "13. Final regression",
    items: [
      {
        id: "F01",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Edit re-triggers approval / refund / pause persist",
        issue: "Edits → Awaiting Approval; withdraw doesn't refund token; pause doesn't persist; unblock not in Browse.",
        fix: "Keep approved status on edits; refund 1 token once on withdraw; persist pause server-side; see S06.",
        note: "Edits keep Approved status (changes time-stamped in edited_since_review_at for admin); withdraw refunds 1 token; Pause saves instantly server-side and ordinary saves no longer un-pause; unblock verified (see S06).",
      },
      {
        id: "F02",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Login persistence",
        issue: "Same as F01 after re-login.",
        fix: "See F01.",
        dupOf: "F01",
        note: "Resolved with F01 — all server-side, survives logout/login.",
      },
      {
        id: "F03",
        pri: "CRIT",
        qa: "FAIL",
        status: "done",
        title: "Two-tab race",
        issue: "Same as K05.",
        fix: "See K05.",
        dupOf: "K05",
        note: "Resolved with K05.",
      },
      {
        id: "F04",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Basic/Gold separation",
        issue: "Same as B09.",
        fix: "See B09.",
        dupOf: "B09",
        note: "Resolved with B09.",
      },
      {
        id: "F07",
        pri: "HIGH",
        qa: "FAIL",
        status: "done",
        title: "Android Chrome / PWA smoke",
        issue: "Chat keyboard, swipe, foreground banners.",
        fix: "See K09, C11, N01.",
        dupOf: "K09",
        note: "Chat keyboard (K09) + swipe (C11) fixed; foreground banner done earlier. Needs an Android Chrome/PWA smoke retest.",
      },
    ],
  },
];

export function qaStats(items: QaItem[] = qaSections.flatMap((s) => s.items)) {
  const done = items.filter((i) => i.status === "done").length;
  const inProgress = items.filter((i) => i.status === "in_progress").length;
  const todo = items.length - done - inProgress;
  const critOpen = items.filter((i) => i.pri === "CRIT" && i.status !== "done").length;
  const pct = items.length ? Math.round((done / items.length) * 100) : 0;
  return { total: items.length, done, inProgress, todo, critOpen, pct };
}
